import { BloqueMeta } from "./types";

export const SITE_CONFIG = {
  name: "Atlas IA",
  description: "La mejor plataforma en español para aprender Inteligencia Artificial",
  url: "https://atlas-ia-psi.vercel.app",
  author: "Atlas IA",
  contactEmail: "privacidad@atlas-ia.dev",
  contactName: "Noemí Celaya Mingot",
} as const;

export const BLOQUES: BloqueMeta[] = [
  {
    slug: "antes-de-empezar",
    numero: 0,
    titulo: "Antes de Empezar",
    descripcion: "Introducción y cómo aprovechar al máximo esta plataforma",
    icono: "Compass",
    color: "primary",
    lecciones: 6,
  },
  {
    slug: "fundamentos",
    numero: 1,
    titulo: "Fundamentos de IA",
    descripcion: "Conceptos esenciales: Machine Learning, Deep Learning, LLM, Transformers y más",
    icono: "Brain",
    color: "purple",
    lecciones: 10,
  },
  {
    slug: "ecosistema",
    numero: 2,
    titulo: "Mapa del Ecosistema",
    descripcion: "Explora las principales herramientas de IA y compara entre ellas",
    icono: "Globe",
    color: "accent",
    lecciones: 8,
  },
  {
    slug: "prompting",
    numero: 3,
    titulo: "Ingeniería de Prompt",
    descripcion: "Domina el arte de comunicarte de forma eficaz con la IA",
    icono: "MessageSquare",
    color: "primary",
    lecciones: 8,
  },
  {
    slug: "ia-docencia",
    numero: 4,
    titulo: "IA Aplicada a la Docencia",
    descripcion: "Herramientas y técnicas para transformar la enseñanza con IA",
    icono: "GraduationCap",
    color: "accent",
    lecciones: 7,
  },
  {
    slug: "ia-multimodal",
    numero: 5,
    titulo: "IA Multimodal",
    descripcion: "Imagen, vídeo, audio y presentaciones con inteligencia artificial",
    icono: "Image",
    color: "purple",
    lecciones: 6,
  },
  {
    slug: "programacion",
    numero: 6,
    titulo: "Programación Asistida",
    descripcion: "Cursor, Copilot, Claude Code y más herramientas para desarrolladores",
    icono: "Code",
    color: "primary",
    lecciones: 6,
  },
  {
    slug: "agentes",
    numero: 7,
    titulo: "Agentes y Automatización",
    descripcion: "MCP, RAG, agentes autónomos y automatización de flujos de trabajo",
    icono: "Bot",
    color: "purple",
    lecciones: 8,
  },
  {
    slug: "etica",
    numero: 8,
    titulo: "Ética y Responsabilidad",
    descripcion: "Privacidad, RGPD, derechos de autor y uso responsable de la IA",
    icono: "Shield",
    color: "accent",
    lecciones: 6,
  },
  {
    slug: "laboratorio",
    numero: 9,
    titulo: "Laboratorio",
    descripcion: "Experimentos, comparativas, retos y casos reales",
    icono: "FlaskConical",
    color: "primary",
    lecciones: 5,
  },
  {
    slug: "novedades",
    numero: 10,
    titulo: "Novedades",
    descripcion: "Noticias, nuevos modelos, actualizaciones y tendencias del ecosistema",
    icono: "Sparkles",
    color: "purple",
    lecciones: 6,
  },
];

export const NAV_ITEMS = [
  { href: "/", label: "Inicio", icon: "Home" },
  { href: "/bloques", label: "Bloques", icon: "BookOpen" },
  { href: "/cronologia", label: "Cronología", icon: "Calendar" },
  { href: "/glosario", label: "Glosario", icon: "BookMarked" },
  { href: "/laboratorio", label: "Laboratorio", icon: "FlaskConical" },
  { href: "/perfil", label: "Mi perfil", icon: "User" },
] as const;
