import {
  HerramientaIA,
  CategoriaHerramienta,
  CriterioComparacion,
  DecisionNode,
} from "./types";

export const CATEGORIAS: Record<
  CategoriaHerramienta,
  { nombre: string; descripcion: string; icono: string }
> = {
  "asistente-conversacion": {
    nombre: "Asistentes de Conversación",
    descripcion: "Chatbots generales que responden preguntas y ayudan con tareas variadas",
    icono: "💬",
  },
  codigo: {
    nombre: "Herramientas de Código",
    descripcion: "Asistentes para programar, depurar y desarrollar software",
    icono: "💻",
  },
  imagen: {
    nombre: "Generación de Imágenes",
    descripcion: "Herramientas que crean imágenes a partir de texto o las editan",
    icono: "🎨",
  },
  "audio-video": {
    nombre: "Audio y Vídeo",
    descripcion: "IA para crear, editar o transformar audio y vídeo",
    icono: "🎵",
  },
  "no-code": {
    nombre: "Plataformas No-Code",
    descripcion: "Plataformas para crear aplicaciones y automatizaciones sin programar",
    icono: "🧩",
  },
  productividad: {
    nombre: "Productividad",
    descripcion: "Herramientas para organizar, resumir y trabajar más rápido",
    icono: "⚡",
  },
  investigacion: {
    nombre: "Investigación",
    descripcion: "Herramientas académicas y de búsqueda avanzada",
    icono: "🔬",
  },
};

export const HERRAMIENTAS: HerramientaIA[] = [
  {
    id: "chatgpt",
    nombre: "ChatGPT",
    empresa: "OpenAI",
    categoria: "asistente-conversacion",
    descripcion: "El asistente de IA más popular del mundo. Versátil, fácil de usar y con integración en múltiples plataformas.",
    caracteristicas: [
      "Conversación natural fluida",
      "Multimodal: texto, imágenes, audio",
      "GPT-4o con razonamiento avanzado",
      "Plugins y GPTs personalizados",
      "Integración con navegación web y código",
      "Memoria entre conversaciones",
    ],
    idealPara: ["Uso general", "Preguntas rápidas", "Escritura creativa", "Análisis básico"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, Plus $20/mes, Pro $200/mes",
    url: "https://chat.openai.com",
    openSource: false,
    multimodal: true,
    ventanaContexto: "128K tokens",
    fortalezaPrincipal: "Versatilidad y facilidad de uso",
    debilidadPrincipal: "Puede ser impreciso en análisis muy profundos",
    popularidad: 10,
  },
  {
    id: "claude",
    nombre: "Claude",
    empresa: "Anthropic",
    categoria: "asistente-conversacion",
    descripcion: "Conocido por su capacidad de análisis profundo y sus respuestas matizadas. Excelente con documentos largos.",
    caracteristicas: [
      "Ventana de contexto de 200K tokens",
      "Análisis profundo y detallado",
      "Excelente con código",
      "Mayor precisión y menos alucinaciones",
      "Modo de escritura cuidada",
      "Proyecto con documentos personalizados",
    ],
    idealPara: ["Análisis de documentos", "Programación", "Escritura técnica", "Investigación"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, Pro $20/mes",
    url: "https://claude.ai",
    openSource: false,
    multimodal: true,
    ventanaContexto: "200K tokens",
    fortalezaPrincipal: "Profundidad de análisis y precisión",
    debilidadPrincipal: "Menos integraciones de terceros",
    popularidad: 9,
  },
  {
    id: "gemini",
    nombre: "Gemini",
    empresa: "Google",
    categoria: "asistente-conversacion",
    descripcion: "El asistente multimodal de Google con una ventana de contexto enorme e integración con todo el ecosistema Google.",
    caracteristicas: [
      "Contexto de hasta 2 millones de tokens",
      "Integrado con Google Workspace",
      "Excelente con imágenes y vídeo",
      "Acceso a información en tiempo real",
      "Búsqueda Google integrada",
      "Gemini Advanced con Deep Think",
    ],
    idealPara: ["Documentos extensos", "Google Workspace", "Búsquedas", "Análisis multimodal"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, Advanced $20/mes",
    url: "https://gemini.google.com",
    openSource: false,
    multimodal: true,
    ventanaContexto: "2M tokens",
    fortalezaPrincipal: "Contexto enorme y ecosistema Google",
    debilidadPrincipal: "A veces menos preciso en análisis detallado",
    popularidad: 9,
  },
  {
    id: "copilot",
    nombre: "GitHub Copilot",
    empresa: "GitHub/Microsoft",
    categoria: "codigo",
    descripcion: "El asistente de código más extendido. Se integra directamente en tu editor y sugiere código en tiempo real.",
    caracteristicas: [
      "Sugerencias de código en tiempo real",
      "Chat integrado en el editor",
      "Autocompletado inteligente",
      "Soporte para múltiples lenguajes",
      "Copilot X con multimodal",
      "Integración nativa con VS Code",
    ],
    idealPara: ["Desarrolladores", "Aprendizaje de código", "Productividad en programación"],
    precio: "pago",
    precioDetalle: "$10/mes individual, $19/mes business",
    url: "https://github.com/features/copilot",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Integración directa en el editor",
    debilidadPrincipal: "Solo para código, no para otras tareas",
    popularidad: 9,
  },
  {
    id: "cursor",
    nombre: "Cursor",
    empresa: "Cursor Inc.",
    categoria: "codigo",
    descripcion: "Editor de código con IA integrada. Un VS Code potenciado con capacidades de IA nativas.",
    caracteristicas: [
      "Editor completo con IA nativa",
      "Composer para cambios en varios archivos",
      "Chat con contexto del proyecto",
      "Generación de código avanzada",
      "Modo agente para tareas complejas",
      "Basado en VS Code (compatible)",
    ],
    idealPara: ["Desarrollo completo", "Proyectos grandes", "Refactorización"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, Pro $20/mes",
    url: "https://cursor.sh",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Profunda integración de la IA en la edición de código",
    debilidadPrincipal: "Requiere aprendizaje inicial",
    popularidad: 8,
  },
  {
    id: "dalle",
    nombre: "DALL-E 3",
    empresa: "OpenAI",
    categoria: "imagen",
    descripcion: "Generador de imágenes integrado en ChatGPT. Crea imágenes a partir de descripciones detalladas.",
    caracteristicas: [
      "Generación desde texto detallado",
      "Integrado en ChatGPT",
      "Edición de imágenes",
      "Buena comprensión de prompts",
      "Estilos variados",
      "Uso comercial permitido",
    ],
    idealPara: ["Ilustraciones", "Prototipos visuales", "Contenido para redes"],
    precio: "pago",
    precioDetalle: "Incluido en ChatGPT Plus",
    url: "https://openai.com/dall-e-3",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Fácil de usar con prompts en lenguaje natural",
    debilidadPrincipal: "Menos control preciso que Midjourney",
    popularidad: 8,
  },
  {
    id: "midjourney",
    nombre: "Midjourney",
    empresa: "Midjourney Inc.",
    categoria: "imagen",
    descripcion: "Generador de imágenes de alta calidad artística. Conocido por su estética excepcional.",
    caracteristicas: [
      "Calidad artística superior",
      "Múltiples estilos artísticos",
      "Generación rápida",
      "Escalado de resolución avanzado",
      "Variaciones y remix",
      "Comunidad activa de Discord",
    ],
    idealPara: ["Arte digital", "Conceptos visuales", "Diseño gráfico"],
    precio: "pago",
    precioDetalle: "Planes desde $10/mes",
    url: "https://midjourney.com",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Calidad estética excepcional",
    debilidadPrincipal: "Sin interfaz web completa (aún)",
    popularidad: 8,
  },
  {
    id: "stable-diffusion",
    nombre: "Stable Diffusion",
    empresa: "Stability AI",
    categoria: "imagen",
    descripcion: "Generador de imágenes open source. Ejecutable localmente con control total sobre el proceso.",
    caracteristicas: [
      "Completamente open source",
      "Ejecutable localmente",
      "Control total del proceso",
      "Múltiples interfaces (Automatic1111, ComfyUI)",
      "Modelos personalizables",
      "Sin costes de API",
    ],
    idealPara: ["Desarrolladores", "Artistas técnicos", "Uso personalizado"],
    precio: "gratis",
    precioDetalle: "Gratis (necesitas hardware potente)",
    url: "https://stability.ai",
    openSource: true,
    multimodal: false,
    fortalezaPrincipal: "Gratuito y personalizable",
    debilidadPrincipal: "Requiere conocimientos técnicos",
    popularidad: 7,
  },
  {
    id: "elevenlabs",
    nombre: "ElevenLabs",
    empresa: "ElevenLabs",
    categoria: "audio-video",
    descripcion: "Plataforma líder en síntesis de voz con IA. Clonación de voz y generación de audio ultrarealista.",
    caracteristicas: [
      "Voces ultrarealistas",
      "Clonación de voz",
      "Multiidioma",
      "Audiolibros y pódcast",
      "API para desarrolladores",
      "Ajustes de emoción y tono",
    ],
    idealPara: ["Pódcast", "Audiolibros", "Contenido audiovisual", "Accesibilidad"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, planes desde $5/mes",
    url: "https://elevenlabs.io",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Calidad de voz más realista del mercado",
    debilidadPrincipal: "Coste escalado para uso intensivo",
    popularidad: 8,
  },
  {
    id: "runway",
    nombre: "Runway",
    empresa: "Runway ML",
    categoria: "audio-video",
    descripcion: "Plataforma de creación de vídeo con IA. Desde generación hasta edición con Gen-3 Alpha.",
    caracteristicas: [
      "Generación de vídeo desde texto",
      "Edición de vídeo con IA",
      "Gen-3 Alpha de alta calidad",
      "Motion Brush para controlar el movimiento",
      "Integración con After Effects",
      "Herramientas de composición",
    ],
    idealPara: ["Creadores de contenido", "Videógrafos", "Publicidad"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, planes desde $12/mes",
    url: "https://runwayml.com",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Edición de vídeo con IA avanzada",
    debilidadPrincipal: "Coste alto para uso profesional",
    popularidad: 7,
  },
  {
    id: "notion-ai",
    nombre: "Notion AI",
    empresa: "Notion",
    categoria: "productividad",
    descripcion: "IA integrada en Notion para escritura, organización y gestión del conocimiento.",
    caracteristicas: [
      "Resumen de documentos",
      "Generación de contenido",
      "Traducción integrada",
      "Búsqueda semántica",
      "Autocompletado inteligente",
      "Integración con bases de datos",
    ],
    idealPara: ["Gestión de conocimiento", "Documentación", "Organización personal"],
    precio: "pago",
    precioDetalle: "$10/mes por usuario (con Notion)",
    url: "https://notion.so",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Integración perfecta con Notion",
    debilidadPrincipal: "Solo funciona dentro de Notion",
    popularidad: 7,
  },
  {
    id: "perplexity",
    nombre: "Perplexity",
    empresa: "Perplexity AI",
    categoria: "investigacion",
    descripcion: "Motor de búsqueda con IA que cita sus fuentes. Ideal para investigación profunda y verificable.",
    caracteristicas: [
      "Búsqueda con citas de fuentes",
      "Pro Search para preguntas complejas",
      "Modo Académico",
      "Imágenes y tablas en resultados",
      "Colaboración en espacios",
      "API para desarrolladores",
    ],
    idealPara: ["Investigación", "Estudiantes", "Profesionales", "Periodismo"],
    precio: "freemium",
    precioDetalle: "Gratis limitado, Pro $20/mes",
    url: "https://perplexity.ai",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Citas verificables y transparencia",
    debilidadPrincipal: "Puede ser menos creativo que ChatGPT",
    popularidad: 8,
  },
  {
    id: "make",
    nombre: "Make (ex-Integromat)",
    empresa: "Make",
    categoria: "no-code",
    descripcion: "Plataforma visual de automatización. Conecta aplicaciones y crea flujos de trabajo complejos sin código.",
    caracteristicas: [
      "Automatización visual por escenarios",
      "Miles de integraciones",
      "Lógica condicional avanzada",
      "IA generativa integrada",
      "Plantillas predefinidas",
      "Ejecución en tiempo real",
    ],
    idealPara: ["Automatización de procesos", "Marketing", "Emprendedores"],
    precio: "freemium",
    precioDetalle: "Gratis (1000 operaciones/mes), desde $9/mes",
    url: "https://make.com",
    openSource: false,
    multimodal: false,
    fortalezaPrincipal: "Flexibilidad visual sin código",
    debilidadPrincipal: "Curva de aprendizaje para escenarios complejos",
    popularidad: 7,
  },
];

export const CRITERIOS_COMPARACION: CriterioComparacion[] = [
  {
    id: "facilidad-uso",
    nombre: "Facilidad de uso",
    descripcion: "Cuán fácil es empezar a usar la herramienta",
    opciones: ["Principiante", "Intermedio", "Avanzado"],
  },
  {
    id: "calidad-respuesta",
    nombre: "Calidad de respuesta",
    descripcion: "Precisión y utilidad de las respuestas generadas",
    opciones: ["Básica", "Buena", "Excelente"],
  },
  {
    id: "velocidad",
    nombre: "Velocidad",
    descripcion: "Cuán rápido genera respuestas",
    opciones: ["Lenta", "Media", "Rápida"],
  },
  {
    id: "precio",
    nombre: "Precio",
    descripcion: "Relación calidad-precio",
    opciones: ["Caro", "Razonable", "Barato/Gratis"],
  },
  {
    id: "personalizacion",
    nombre: "Personalización",
    descripcion: "Capacidad de adaptar la herramienta a necesidades concretas",
    opciones: ["Básica", "Media", "Alta"],
  },
];

export const ARBOL_DECISION: DecisionNode[] = [
  {
    id: "inicio",
    pregunta: "¿Qué necesitas hacer?",
    descripcion: "Selecciona la tarea principal que quieres realizar",
    opciones: [
      { texto: "Conversar y hacer preguntas", siguienteNodoId: "conversacion" },
      { texto: "Programar o desarrollar software", siguienteNodoId: "codigo" },
      { texto: "Crear imágenes o diseños", siguienteNodoId: "imagen" },
      { texto: "Trabajar con audio o vídeo", siguienteNodoId: "audio-video" },
      { texto: "Automatizar procesos", herramientaRecomendada: "make" },
      { texto: "Investigar información", herramientaRecomendada: "perplexity" },
    ],
  },
  {
    id: "conversacion",
    pregunta: "¿Qué tipo de conversación necesitas?",
    descripcion: "Cada asistente es mejor para unas tareas u otras",
    opciones: [
      { texto: "Respuestas rápidas y uso general", herramientaRecomendada: "chatgpt" },
      { texto: "Análisis profundo de documentos", herramientaRecomendada: "claude" },
      { texto: "Acceder a información actualizada", herramientaRecomendada: "gemini" },
      { texto: "Investigación con fuentes verificadas", herramientaRecomendada: "perplexity" },
    ],
  },
  {
    id: "codigo",
    pregunta: "¿Qué prefieres para programar?",
    descripcion: "Hay diferentes enfoques según tu estilo de trabajo",
    opciones: [
      { texto: "Sugerencias en mi editor actual", herramientaRecomendada: "copilot" },
      { texto: "Un editor completo con IA", herramientaRecomendada: "cursor" },
      { texto: "Asistente general para código", herramientaRecomendada: "chatgpt" },
    ],
  },
  {
    id: "imagen",
    pregunta: "¿Qué tipo de imágenes necesitas?",
    descripcion: "Cada herramienta tiene fortalezas diferentes en generación visual",
    opciones: [
      { texto: "Rápido y fácil desde texto", herramientaRecomendada: "dalle" },
      { texto: "Alta calidad artística", herramientaRecomendada: "midjourney" },
      { texto: "Control total y gratuito", herramientaRecomendada: "stable-diffusion" },
    ],
  },
  {
    id: "audio-video",
    pregunta: "¿Qué necesitas crear?",
    descripcion: "Las herramientas de IA para audio y vídeo están en rápida evolución",
    opciones: [
      { texto: "Voces y narración", herramientaRecomendada: "elevenlabs" },
      { texto: "Vídeos con IA", herramientaRecomendada: "runway" },
    ],
  },
];

export function getHerramientasPorCategoria(
  categoria: CategoriaHerramienta
): HerramientaIA[] {
  return HERRAMIENTAS.filter((h) => h.categoria === categoria);
}

export function getHerramientaPorId(id: string): HerramientaIA | undefined {
  return HERRAMIENTAS.find((h) => h.id === id);
}

export function getNodoDecision(id: string): DecisionNode | undefined {
  return ARBOL_DECISION.find((n) => n.id === id);
}
